<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Modules.Wikis.Infrastructure.Data.EF\App.Modules.Wikis.Infrastructure.Data.EF.csproj" />
    <ProjectReference Include="..\App.Modules.Wikis.Interfaces.API.GraphQL\App.Modules.Wikis.Interfaces.API.GraphQL.csproj" />
    <ProjectReference Include="..\App.Modules.Wikis.Interfaces.API.OData\App.Modules.Wikis.Interfaces.API.OData.csproj" />
    <ProjectReference Include="..\App.Modules.Wikis.Interfaces.API.REST\App.Modules.Wikis.Interfaces.API.REST.csproj" />
  </ItemGroup>

</Project>
