// <auto-generated />
using System;
using App.Modules.Wikis.Infrastructure.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.Wikis.Infrastructure.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    [Migration("20260617072454_RenamePublicWikiRootToRepo1")]
    partial class RenamePublicWikiRootToRepo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wikis")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.Wiki", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(11)
                        .HasComment("The textual Description.");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(12)
                        .HasComment("Get/Set whether the entity is enabled or not.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnOrder(9)
                        .HasComment("Get/Set the list item's unique key.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<Guid?>("OwnerWorkspaceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(13)
                        .HasComment("Opaque identifier for the related Owner Workspace aggregate.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(10)
                        .HasComment("The (display) title.");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_Wiki_Enabled");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Wiki_Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Wikis_Key");

                    b.HasIndex("OwnerWorkspaceId")
                        .HasDatabaseName("IX_Wiki_OwnerWorkspaceId");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_Wiki_RecordState");

                    b.ToTable("Wikis", "wikis_wikis", t =>
                        {
                            t.HasComment("A Wiki is a single, independently mountable wiki root (a \"space\"). It is the top of the page tree: every belongs to exactly one Wiki, and the is the stable mount key (the namespace segment used in wiki:{key}:{slug} cross-links and in routing). Multiple wikis can co-exist on the platform (per ADR-018H multi-root), so domain-neutral key + title + description is all that is modelled here; everything richer hangs off the pages.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f61873b-7862-dd7c-ee16-0da2e9700172"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Shared, cross-cutting knowledge common to everyone.",
                            Enabled = true,
                            Key = "commons",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RecordState = 4,
                            Title = "Commons"
                        },
                        new
                        {
                            Id = new Guid("459b165f-0a68-e67f-37cb-0b8720e28494"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Developer documentation, spikes, and engineering notes.",
                            Enabled = true,
                            Key = "developers",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RecordState = 4,
                            Title = "Developers"
                        },
                        new
                        {
                            Id = new Guid("46d654b0-5a0b-45d4-6e20-3cc93ea72d2d"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Internal, organisation-facing wiki space.",
                            Enabled = true,
                            Key = "intranet",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RecordState = 4,
                            Title = "Intranet"
                        },
                        new
                        {
                            Id = new Guid("c88f756c-e1b6-2d6a-5ed3-61c4964642bd"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The default wiki document store.",
                            Enabled = true,
                            Key = "repo1",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RecordState = 4,
                            Title = "Repository 1"
                        },
                        new
                        {
                            Id = new Guid("07db6a3f-bde1-d772-d162-36a69635611e"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Reference material and resource documentation.",
                            Enabled = true,
                            Key = "resources",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RecordState = 4,
                            Title = "Resources"
                        },
                        new
                        {
                            Id = new Guid("7eee4e19-a93e-6eeb-71d6-79876fe9b55c"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Configuration and administration guidance.",
                            Enabled = true,
                            Key = "settings",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnDateTimeUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RecordState = 4,
                            Title = "Settings"
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiAcl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(11)
                        .HasComment("The permission key granted, e.g. Wiki:Read or WikiPage:Write, composed from permission constants rather than a magic string at the call site.");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9)
                        .HasComment("The identifier of the principal the grant is issued to. Interpreted together with .");

                    b.Property<int>("PrincipalType")
                        .HasColumnType("int")
                        .HasColumnOrder(10)
                        .HasComment("The kind of principal (User, Group, Workspace, or Everyone), stored as the integer of the shared PrincipalType contract to avoid a hard enum dependency leaking into this Shared model.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<Guid?>("WikiFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to the root this grant applies to, when the grant is wiki-wide. null when the grant is page-scoped.");

                    b.Property<Guid?>("WikiPageFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to the this grant applies to, when the grant is page-scoped. null when the grant is wiki-wide.");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiAcl_Id");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiAcl_RecordState");

                    b.HasIndex("WikiFK");

                    b.HasIndex("WikiPageFK");

                    b.HasIndex("PrincipalId", "PrincipalType")
                        .HasDatabaseName("IX_WikiAcls_PrincipalId_PrincipalType");

                    b.ToTable("WikiAcls", "wikis_wikis", t =>
                        {
                            t.HasComment("An access-control entry binding a principal to a permission on a wiki scope, following the framework's share-based access pattern (a TenantId-per-row model is an explicit anti-pattern here). Access is granted by issuing WikiAcl rows to principals rather than by owning a tenant. The / pair identifies who the grant is for (User, Group, Workspace, or Everyone). Exactly one scope FK is populated: an ACL applies either to a whole () or to a single (); the page-level grant is the more specific override. Every resolver applies the reader's grants and must never act as an existence/content oracle for content the reader cannot see.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11)
                        .HasComment("Identifier of the immutable object-store blob holding the media bytes.");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(13)
                        .HasComment("The content hash of the media blob, used for drift detection and to support re-verification of baked endorsement badges (ADR-018M).");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(10)
                        .HasComment("The textual Description.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(12)
                        .HasComment("The IANA media (MIME) type of the blob, e.g. image/png or image/svg+xml.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<Guid?>("SourceMediaFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(14)
                        .HasComment("Optional self-referential FK to the source media artifact this row was rendered from, used for the draw.io two-artifact pair (ADR-018, §10 of the body-storage implementation note). On a render artifact (e.g. a flattened image/svg+xml, see ) this points at the editable source artifact (e.g. the application/vnd.jgraph.mxfile, see ) the editor reopens for edit. On a source artifact (or any plain media) this is null. Navigable, so the suffix is FK, not Id. Keeping both artifacts as rows preserves a single ACL surface, a single immutable-blob lifecycle, and a single storage path derivation for the diagram pair.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(9)
                        .HasComment("The (display) title.");

                    b.Property<Guid>("WikiPageFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to the owning this media is attached to. Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiMedia_Id");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiMedia_RecordState");

                    b.HasIndex("SourceMediaFK")
                        .HasDatabaseName("IX_WikiMedia_SourceMediaFK");

                    b.HasIndex("WikiPageFK")
                        .HasDatabaseName("IX_WikiMedia_WikiPageFK");

                    b.ToTable("WikiMedia", "wikis_wikis", t =>
                        {
                            t.HasComment("A media asset that lives in the vicinity of a (images, diagrams, baked badge images, draw.io SVG, etc.). Like page bodies, media is an immutable blob (ADR-018): \"replace\" means a new and a repoint, never an in-place mutation. This row is the addressable, ACL-able handle for the blob; the bytes themselves are held by the object store via Sys.Infrastructure.Media.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiNodeStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("BackgroundMediaName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(11)
                        .HasComment("Logical page-vicinity media name (for example, media:hero.png) used as the bounded background asset reference.");

                    b.Property<int>("ContrastMode")
                        .HasColumnType("int")
                        .HasColumnOrder(13)
                        .HasComment("Bounded text contrast mode controlling the foreground treatment over the background image.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<int>("OverlayOpacityMode")
                        .HasColumnType("int")
                        .HasColumnOrder(12)
                        .HasComment("Bounded overlay opacity mode controlling how strongly the background image is muted behind foreground content.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(10)
                        .HasComment("Stable section key (markdown heading slug / rendered heading id) this style applies to. Null or empty means the style decorates the whole page wrapper rather than one specific section.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<Guid>("WikiPageFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(14)
                        .HasComment("FK to the owning whose rendered output this style decorates.");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiNodeStyle_Id");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiNodeStyle_RecordState");

                    b.HasIndex("WikiPageFK")
                        .HasDatabaseName("IX_WikiNodeStyle_WikiPageFK");

                    b.HasIndex("WikiPageFK", "SectionKey")
                        .IsUnique()
                        .HasFilter("[SectionKey] IS NOT NULL");

                    b.ToTable("WikiNodeStyles", "wikis_wikis", t =>
                        {
                            t.HasComment("Additive page-scoped style row describing a bounded section or page-level background presentation (ADR-018D §2.2, build-plan Phase D step 16).");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(15)
                        .HasComment("Opaque identifier for the related Current Version aggregate.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(10)
                        .HasComment("The textual Description.");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(11)
                        .HasComment("Get/Set whether the entity is enabled or not.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<Guid?>("ParentWikiPageFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Optional FK to a parent . Non-authoritative for addressing. Ancestry is derived from (split on /); this column is retained only as an optional explicit parent link and is null for a top-level page. A page whose path-parent does not yet exist is valid (DokuWiki-style): navigating there yields a blank page that is an invitation to create it.");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(13)
                        .HasComment("The canonical, full namespace path of this page within its (e.g. engineering/onboarding/setup), unique within the wiki root. This is the single source of truth for addressing (DokuWiki-style): the prefix up to the last / is the \"namespace\" and the final segment is the leaf. There is no separate namespace entity. is merely the derived last segment of this path. Path is canonical and may itself be non-URL-safe; the render layer is responsible for URL-mangling it for safe links and copy. Full-text/prefix search runs against this field.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(14)
                        .HasComment("The derived last segment (leaf) of , unique within its . Retained for routing and wiki:{key}:{slug} cross-links; it is computed from and is not an independent authority.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(9)
                        .HasComment("The (display) title.");

                    b.Property<Guid>("WikiFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(12)
                        .HasComment("FK to the owning root. Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("IX_WikiPage_CurrentVersionId");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_WikiPage_Enabled");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiPage_Id");

                    b.HasIndex("ParentWikiPageFK");

                    b.HasIndex("Path")
                        .HasDatabaseName("IX_WikiPages_Path");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiPage_RecordState");

                    b.HasIndex("WikiFK", "Path")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiPages_WikiFK_Path");

                    b.HasIndex("WikiFK", "Slug")
                        .HasDatabaseName("IX_WikiPages_WikiFK_Slug");

                    b.ToTable("WikiPages", "wikis_wikis", t =>
                        {
                            t.HasComment("A WikiPage is the stable identity of a page within a . It is deliberately thin: it owns the addressing (the canonical ) and points at the current published version, but it carries no body text. All body content is immutable and lives in rows (ADR-018 immutable-blob invariant), so \"editing a page\" never mutates this row's content — it appends a new version and repoints . Addressing is DokuWiki-style: is the source of truth (prefix = namespace, last segment = leaf). is the derived leaf and is an optional, non-authoritative explicit parent link — ancestry and children are derived from the path.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<Guid>("BodyBlobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11)
                        .HasComment("The sink-agnostic body locator for this version's raw body bytes (ADR-018N §2.6). Its concrete meaning depends on the active body sink: the PK of the WikiPageVersionBody satellite row (Database sink), the object-store blob id (ObjectStore sink), or a deterministic handle from which the content-repo file path is derived (FileSystem sink). Replacing content means a new locator on a new version row, never a mutation of an existing one.");

                    b.Property<string>("ContentFormatKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(13)
                        .HasComment("The declared content format of the body (e.g. markdown), per the ADR-018E content-format DSL. Stored as a key so the parser-selection seam can resolve the right parser without a hard enum dependency at this layer.");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(12)
                        .HasComment("The content hash of the body. Computed identically across every body sink so a mirrored copy can be verified equal; used for staleness/drift detection and as the subject a verifiable endorsement (ADR-018M) is pinned to.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnOrder(10)
                        .HasComment("Monotonic version number within the page (1-based). Combined with it uniquely identifies a revision.");

                    b.Property<Guid>("WikiPageFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9)
                        .HasComment("FK to the owning . Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiPageVersion_Id");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiPageVersion_RecordState");

                    b.HasIndex("WikiPageFK", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiPageVersions_WikiPageFK_VersionNumber");

                    b.ToTable("WikiPageVersions", "wikis_wikis", t =>
                        {
                            t.HasComment("An immutable snapshot of a 's content at a point in time. This is the heart of the ADR-018 immutability invariant: a version is never edited in place. \"Editing\" appends a new WikiPageVersion and repoints . The body itself is not stored inline; is the sink-agnostic body locator (ADR-018N §2.6) addressing the version's raw body bytes in whichever body-storage sink is configured — a WikiPageVersionBody satellite row (Database sink), an immutable object-store blob (ObjectStore sink), or an external content-repo file (FileSystem sink). is the sink-independent content hash of those bytes and is what an Open-Badges / VC endorsement (ADR-018M) pins to, so a badge can be proven to be \"for this exact version\" regardless of where the bytes physically live.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersionBody", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("Body")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10)
                        .HasComment("The raw text body of the version, in the format declared by the version's ContentFormatKey (ADR-018E). Stored as unbounded Unicode text so it is full-text indexable in place.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<Guid>("WikiPageVersionFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9)
                        .HasComment("FK to the owning (1:1). Under the Database sink this also equals the version's body locator (BodyBlobId), so the body can be fetched directly from the version's stored locator without a second lookup key. Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiPageVersionBody_Id");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiPageVersionBody_RecordState");

                    b.HasIndex("WikiPageVersionFK")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiPageVersionBodies_WikiPageVersionFK");

                    b.ToTable("WikiPageVersionBodies", "wikis_wikis", t =>
                        {
                            t.HasComment("The bytes-bearing satellite row for the Database body storage sink (ADR-018N §2.2, Seam 1). It holds the raw text body of exactly one , 1:1, via a foreign key into the version — it never alters the core row, in keeping with the ADR-018 §2.7 additive-tables seam.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("ContentFormatKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(13)
                        .HasComment("The declared content format the template scaffolds in (per the ADR-018E content-format DSL, e.g. markdown). New pages created from this template start in this format so the editor emits a declared format from the outset.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(11)
                        .HasComment("The textual Description.");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(12)
                        .HasComment("Get/Set whether the entity is enabled or not.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnOrder(9)
                        .HasComment("Get/Set the list item's unique key.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(10)
                        .HasComment("The (display) title.");

                    b.Property<Guid>("WikiFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(14)
                        .HasComment("FK to the owning root the template belongs to. Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_WikiTemplate_Enabled");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplate_Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplate_Key");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiTemplate_RecordState");

                    b.HasIndex("WikiFK")
                        .HasDatabaseName("IX_WikiTemplate_WikiFK");

                    b.HasIndex("WikiFK", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplates_WikiFK_Key");

                    b.ToTable("WikiTemplates", "wikis_wikis", t =>
                        {
                            t.HasComment("A WikiTemplate is a reusable page scaffold (ADR-018C, build-plan Phase D step 15). It defines the shape a new page should start from — an ordered set of blocks (headings + authoring guidance) — and the structural expectations a page is later linted against (advisory by default, never blocking). Templates are themselves authored as pages (\"templates-as-pages\") under the conventional _templates/ namespace, so the same versioning, ACL, and rendering machinery applies to a template as to any page. This row is the structured, queryable projection of that template: the body prose lives in a blob like any page, while the section contract and binding live here so scaffolding and lint can reason about structure without re-parsing prose.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplateBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(9)
                        .HasComment("Get/Set whether the entity is enabled or not.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<int>("PrecedenceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnOrder(10)
                        .HasComment("The deterministic evaluation order for this entity. Lower values are evaluated first. Must be unique within the evaluation context to avoid ambiguous resolution.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("ScopeSlugPrefix")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(13)
                        .HasComment("Optional slug prefix this binding scopes to (e.g. how-to/). Empty when the binding scopes by , or to bind the whole wiki.");

                    b.Property<Guid?>("ScopeWikiPageFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(14)
                        .HasComment("Optional FK to a whose subtree this binding scopes to. null means the binding scopes by instead.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(12)
                        .HasComment("Id of the owning root the binding lives in. Deliberately a non-navigable aggregate id (no Wiki navigation): the binding already cascades from its (which is itself owned by the wiki), so adding a second direct Wiki -> Binding cascade would create multiple cascade paths that SQL Server rejects. This scalar is kept purely as a denormalised scope/query key, mirroring the WikiPage.CurrentVersionId \"plain id to avoid a cycle\" precedent.");

                    b.Property<Guid>("WikiTemplateFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11)
                        .HasComment("FK to the being bound. Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_WikiTemplateBinding_Enabled");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplateBinding_Id");

                    b.HasIndex("PrecedenceOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_WikiTemplateBinding_PrecedenceOrder");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiTemplateBinding_RecordState");

                    b.HasIndex("ScopeWikiPageFK")
                        .HasDatabaseName("IX_WikiTemplateBinding_ScopeWikiPageFK");

                    b.HasIndex("WikiTemplateFK");

                    b.HasIndex("WikiId", "PrecedenceOrder")
                        .HasDatabaseName("IX_WikiTemplateBindings_WikiId_PrecedenceOrder");

                    b.ToTable("WikiTemplateBindings", "wikis_wikis", t =>
                        {
                            t.HasComment("Attaches a to a part of a wiki so new pages there default to that template, and existing pages there are linted against it (ADR-018C, build-plan Phase D step 15). A binding targets either a whole namespace (by slug prefix) or a specific page subtree (by ). When more than one binding could apply, decides which wins — this is logic ordering (which template governs), not display, so it uses .");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(11)
                        .HasComment("The textual Description.");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnOrder(14)
                        .HasComment("Whether the structural lint treats this section as required. When true, a page missing this section's heading raises an advisory lint finding (advisory-by-default — it never blocks saving).");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnOrder(9)
                        .HasComment("Get/Set the list item's unique key.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("PlaceholderBody")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(15)
                        .HasComment("Optional placeholder/guidance prose emitted under the heading when a page is scaffolded from the template. Plain authoring text in the template's declared content format; never executable.");

                    b.Property<int>("PrecedenceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnOrder(12)
                        .HasComment("The deterministic evaluation order for this entity. Lower values are evaluated first. Must be unique within the evaluation context to avoid ambiguous resolution.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(10)
                        .HasComment("The (display) title.");

                    b.Property<Guid>("WikiTemplateFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(13)
                        .HasComment("FK to the owning . Navigable, so the suffix is FK, not Id.");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplateSection_Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplateSection_Key");

                    b.HasIndex("PrecedenceOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_WikiTemplateSection_PrecedenceOrder");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_WikiTemplateSection_RecordState");

                    b.HasIndex("WikiTemplateFK", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_WikiTemplateSections_WikiTemplateFK_Key");

                    b.ToTable("WikiTemplateSections", "wikis_wikis", t =>
                        {
                            t.HasComment("A single ordered block of a scaffold (ADR-018C, build-plan Phase D step 15): a heading plus authoring guidance, and the structural expectation a page is later linted against. The order here is determinate, not cosmetic: it fixes the sequence sections are emitted into a scaffolded page and the sequence the structural lint walks them, so it implements (logic ordering) rather than (display hint). See the DisplayOrderHint/PrecedenceOrder distinction in the house rules.");
                        });
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiAcl", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.Wiki", "Wiki")
                        .WithMany("Acls")
                        .HasForeignKey("WikiFK");

                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", "Page")
                        .WithMany("Acls")
                        .HasForeignKey("WikiPageFK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Page");

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiMedia", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiMedia", "Source")
                        .WithMany()
                        .HasForeignKey("SourceMediaFK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", "Page")
                        .WithMany("Media")
                        .HasForeignKey("WikiPageFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiNodeStyle", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", "Page")
                        .WithMany()
                        .HasForeignKey("WikiPageFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentWikiPageFK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.Wiki", "Wiki")
                        .WithMany("Pages")
                        .HasForeignKey("WikiFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersion", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", "Page")
                        .WithMany("Versions")
                        .HasForeignKey("WikiPageFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersionBody", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersion", "Version")
                        .WithOne("Body")
                        .HasForeignKey("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersionBody", "WikiPageVersionFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplate", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.Wiki", "Wiki")
                        .WithMany()
                        .HasForeignKey("WikiFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplateBinding", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", "ScopePage")
                        .WithMany()
                        .HasForeignKey("ScopeWikiPageFK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplate", "Template")
                        .WithMany("Bindings")
                        .HasForeignKey("WikiTemplateFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScopePage");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplateSection", b =>
                {
                    b.HasOne("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("WikiTemplateFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.Wiki", b =>
                {
                    b.Navigation("Acls");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPage", b =>
                {
                    b.Navigation("Acls");

                    b.Navigation("Children");

                    b.Navigation("Media");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiPageVersion", b =>
                {
                    b.Navigation("Body");
                });

            modelBuilder.Entity("App.Modules.Wikis.Domain.Domains.Wikis.Entities.Implementations.WikiTemplate", b =>
                {
                    b.Navigation("Bindings");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
