<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>$(AssemblyName)</Title>
    <PackageReadmeFile>_Packaging/readme.nuget.md</PackageReadmeFile>
      <PackageReadmeFile>_Packaging/readme.nuget.md</PackageReadmeFile>
      <RootNamespace>App.Modules.Wikis.Infrastructure</RootNamespace>
      <!-- CA1716: Namespace conflicts with reserved keywords like 'Shared', 'Interface' -->
    <NoWarn>$(NoWarn);CA1716;IDE0290;IDE0060;IDE0046;IDE0066;IDE0063;IDE0057;IDE0028;IDE0071;IDE0075;IDE0029;IDE0008</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BASE.Modules.Sys\SOURCE\App.Modules.Sys.Substrate\App.Modules.Sys.Substrate.csproj" />
    <ProjectReference Include="..\App.Modules.Wikis.Domain\App.Modules.Wikis.Domain.csproj" />
    <ProjectReference Include="..\App.Modules.Wikis.Infrastructure\App.Modules.Wikis.Infrastructure.csproj" />
    <ProjectReference Include="..\App.Modules.Wikis.Shared\App.Modules.Wikis.Shared.csproj" />
    <ProjectReference Include="..\..\..\BASE.Modules.Sys\SOURCE\App.Modules.Sys.Infrastructure.Persistence.EF\App.Modules.Sys.Infrastructure.Persistence.EF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="_Packaging\readme.nuget.md">
      <PackagePath>\</PackagePath>
      <Pack>true</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domains\Persistence\Relational\EF\Configuration\" />
    <Folder Include="Domains\Persistence\Relational\EF\Services\Implementations\" />
  </ItemGroup>

</Project>
